name: Build Image

on:
  pull_request:
    paths:
      - Dockerfile
      - production.Dockerfile
      - Gemfile
      - Gemfile.lock
      - app/**
      - config/**
      - bin/**
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - production.Dockerfile
      - Gemfile
      - Gemfile.lock
      - app/**
      - config/**
      - bin/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Production Image
    uses: eckslopez/platform-pipelines/.github/workflows/image-build.yml@main
    with:
      dockerfile: production.Dockerfile
      tags: rigoberta:ci
